CREATE TABLE [dbo].[CartDetail]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT newid(), 
    [CartId] UNIQUEIDENTIFIER NOT NULL,
    [ProductId] UNIQUEIDENTIFIER NOT NULL,
    [ProductPrice] DECIMAL(18,2) NOT NULL,
    [Quantity] INT NOT NULL,
    [CreatedTime] DATETIME DEFAULT GETDATE(),
    [UpdatedTime] DATETIME,
)
