CREATE TABLE [dbo].[OrderDetail]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT newid(), 
    [OrderId] UNIQUEIDENTIFIER NOT NULL, 
    [ProductId] UNIQUEIDENTIFIER NOT NULL, 
    [Quantity] INT NOT NULL, 
    [UnitPrice] INT NOT NULL, 
    [CreatedTime] DATETIME NOT NULL DEFAULT GETDATE(), 
    [UpdatedTime] DATETIME NULL
)
